# name属性用来指定这个工作流的名字
name: Youthstudy-checkin

# 这个部分用来指定能够触发工作流执行的事件
on:
  # 当对分支main进行push操作的时候，这个工作流就被触发了
#   push:
#     branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'



# 工作流是由一个或多个的jobs构成的，在jobs里来说明要交给GitHub aciton执行的任务
jobs:
  # 这个jobs中的一个任务，名字叫build(随便怎么取)
  Youthstudy-checkin:
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest

    # 指出这个build任务的步骤
    steps:
      - name: 检查分支
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x   
          cache: pip
          cache-dependency-path: requirements.txt
      
      - name: Install pip dependencies
        run: pip install -U -r requirements.txt
          
      # 步骤，这里只写了一个步骤，目的是输出hello github acition
      - name: Run Youthstudy
        run: python main.py
